### ISSUE TITLE
Todo for before/after publish

### ISSUE THREAD

**Issue by VasilisThePikachu** [VasilisThePikachu/NewSite#1]
# Before

- [x] Styling for blog list
- [x] Styling for blog itself
- [x] Fix projects tab
- [x] Fill projects tab
- [x] Fork awesome replacement since its deprecated, preferably host icons locally
- [ ] Maybe better title
- [x] Add signal
- [x] Proper title for each page
- [x] Prefer selected pc color theme (also maybe a better bacground)
- [x] Cleanup test blogs
- [x] Setup publish flow, we still using gh pages for now

# After
- [x] Get on furryring
